language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
script:
  - yarn test
before_deploy:
  - npm install netlify-cli -g
  - yarn build
deploy:
  provider: script
  script: netlify deploy --dir=dist --prod
  skip_cleanup: true
  on:
    branch: master
